openapi: 3.0.3
info:
  title: DocCard Markdown Example
  version: 1.0.0
paths:
  /docs:
    get:
      summary: Doc card operation
      description: >
        Returns documentation with **markdown** and <b>HTML</b> in descriptions.
      tags:
        - docCards
      responses:
        "200":
          description: OK
  /docs-admon:
    get:
      summary: Doc card admonition operation
      description: >
        :::info
        Returns documentation with **markdown** and <b>HTML</b> in descriptions inside an admonition.
        :::
      tags:
        - docCards
      responses:
        "200":
          description: OK

tags:
  - name: docCards
    description: This tag shows **markdown** and <b>HTML</b> in the doc card.
