/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the api folder structure
  //   openApiSidebar: require("./api/sidebar").sidebar,
  openApiSidebar: [
    {
      type: "category",
      label: "Petstore",
      link: {
        type: "generated-index",
        title: "Petstore API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/petstore-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "petstore",
        },
      ],
    },
    {
      type: "category",
      label: "Cloud Object Storage",
      link: {
        type: "generated-index",
        title: "Cloud Object Storage API",
        slug: "/category/cos-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "cos",
        },
      ],
    },
    {
      type: "category",
      label: "Food",
      link: {
        type: "generated-index",
        title: "Food APIs",
        slug: "/category/food-apis",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "food",
        },
      ],
    },
    {
      type: "category",
      label: "OpenAPI Issue",
      link: {
        type: "generated-index",
        title: "OpenAPI Issue API",
        slug: "/category/openapi-issue-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "openapi-issue",
        },
      ],
    },
  ],
};

module.exports = sidebars;
