components:
  requestBodies: {}
  securitySchemes:
    x-redlock-auth:
      description: The x-redlock-auth value is a JSON Web Token (JWT).
      in: header
      name: x-redlock-auth
      type: apiKey
  schemas:
    RedLockAuditLogBeanModel:
      description: Model for RedLockAuditLogBean
      properties:
        action:
          type: string
        ipAddress:
          description: IP Address
          type: string
        resourceName:
          type: string
        resourceType:
          type: string
        result:
          type: string
        timestamp:
          description: Timestamp
          format: int64
          type: integer
        user:
          description: User
          type: string
      type: object
info:
  contact: {}
  description:
    "As part of compliance requirement for organizations, companies need\
    \ to demonstrate they are pro-actively \ntracking security issues and taking steps\
    \ to remediate issues as they occur. Prisma Cloud Audit Logs \nsection enables\
    \ companies to prepare for such audits and demonstrates compliance.\n"
  title: Prisma Cloud Audit Logs API Overview
  version: Latest
openapi: 3.0.0
paths:
  /audit/redlock:
    get:
      description:
        Returns audit logs for events that took place on the Prisma Cloud
        platform.
      operationId: rl-audit-logs
      parameters:
        - description: Time Type
          in: query
          name: timeType
          required: false
          schema:
            enum:
              - relative
            type: string
        - description: Time Amount
          in: query
          name: timeAmount
          required: false
          schema:
            format: int32
            type: integer
        - description: Time Unit
          in: query
          name: timeUnit
          required: false
          schema:
            enum:
              - minute
              - hour
              - day
              - week
              - month
              - year
            type: string
      responses:
        "200":
          content:
            application/json; charset=UTF-8:
              schema:
                items:
                  $ref: "#/components/schemas/RedLockAuditLogBeanModel"
                type: array
          description: successful operation
        "400":
          description: bad_request
      security:
        - x-redlock-auth: []
      summary: Prisma Cloud Audit Logs
      tags:
        - Audit Logs
servers:
  - url: https://api.prismacloud.io
tags:
  - description: The Audit Log endpoints are listed below.
    name: Audit Logs
