openapi: 3.0.1
info:
  title: IAM IDP Security API Overview
  description: |
    Prisma Cloud identity and access management (IAM) security integrates with the identity 
    provider (IdP) service Okta to ingest single sign-on (SSO) data for the effective permissions 
    calculation in the IAM Security module.


    See [Integrate Prisma Cloud with Okta](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/prisma-cloud-iam-security/integrate-prisma-cloud-with-okta.html#id2990b78d-1bdc-4090-a716-d899e62db060)
    for more information.

  version: Latest
  contact: {}
servers:
  - url: https://api.prismacloud.io
tags:
  - description: The IAM Identity provider (IDP) security endpoint(s) are below.
    name: IAM IDP Security
paths:
  /api/v1/idp/integration/test:
    post:
      tags:
        - IAM IDP Security
      summary: Test IDP Integration
      operationId: test-integration-with-post
      description: Tests whether or not an integration with Okta is valid.
      parameters:
        - name: id
          in: query
          description: Unique ID of your choice to identify the test. Will override the request parameter **id**.
          schema:
            type: string
      requestBody:
        description: Model for Integration DTO
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IntegrationDto"
        required: true
      security:
        - x-redlock-auth: []
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/IntegrationValidatorResponse"
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
components:
  securitySchemes:
    x-redlock-auth:
      description: The x-redlock-auth value is a JSON Web Token (JWT).
      in: header
      name: x-redlock-auth
      type: apiKey
  schemas:
    IntegrationConfig:
      description: Model for Integration Config
      required:
        - apiToken
        - domain
      type: object
      properties:
        apiToken:
          type: string
          description: Your Okta API token
          example: "11111111111111"
        domain:
          type: string
          description: your Okta domain
          example: my-domain.okta.com
    IntegrationDto:
      description: Model for Integration DTO
      required:
        - integrationConfig
        - integrationType
        - name
      type: object
      properties:
        id:
          type: string
          description: "Unique ID of your choice to identify the test"
          example: test_id
        integrationConfig:
          $ref: "#/components/schemas/IntegrationConfig"
        integrationType:
          type: string
          description: Integration type
          example: OKTA_IDP
          enum:
            - OKTA_IDP
        lastModifiedTs:
          type: integer
          description: "Last modified time (default: N.A.)"
          format: int32
          readOnly: true
          example: 120
        name:
          type: string
          description: Integration name
          example: Integration_name
    IntegrationValidatorResponse:
      description: Model for Integration Validator Response
      type: object
      properties:
        errorMessages:
          type: array
          items:
            $ref: "#/components/schemas/ResponseStatus"
        statusCode:
          type: integer
          format: int32
        success:
          type: boolean
    ResponseStatus:
      description: Model for Response Status
      type: object
      properties:
        i18nKey:
          type: string
        severity:
          type: string
          enum:
            - error
            - info
            - warning
        subject:
          type: string
