components:
  securitySchemes:
    x-redlock-auth:
      description: The x-redlock-auth value is a JSON Web Token (JWT).
      in: header
      name: x-redlock-auth
      type: apiKey
  schemas:
    EventsApiError:
      properties:
        debugMessage:
          type: string
        message:
          type: string
        status:
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
          type: string
        subErrors:
          items:
            $ref: "#/components/schemas/EventsApiSubError"
          type: array
        timestamp:
          format: int64
          type: integer
      type: object
    EventsApiSubError:
      type: object
    EventsCreateTemplateRequest:
      properties:
        integrationId:
          description: Integration Id
          example: 123e4567-e89b-42d3-a456-55664244
          type: string
        integrationType:
          description: Integration type
          enum:
            - email
            - jira
            - service_now
          example: email
          type: string
        name:
          description: Template name
          example: sample-template
          maxLength: 100
          minLength: 5
          pattern: ^[A-Za-z0-9](.){0,99}$
          type: string
        templateConfig:
          additionalProperties:
            description: Template configuration
            items:
              $ref: "#/components/schemas/EventsNotificationFieldsConfig"
            type: array
          description: Template config
          type: object
      required:
        - integrationType
        - name
        - templateConfig
      type: object
    EventsFieldConfigOption:
      properties:
        id:
          description: Field option ID
          type: string
        key:
          description: Field option key
          type: string
        name:
          description: Field option name
          type: string
      type: object
    EventsIntegrationStatusDetails:
      properties:
        details:
          $ref: "#/components/schemas/EventsMessageDetails"
        errorType:
          enum:
            - INVALID_CONFIG
            - TRANSLATION_EXCEPTION
            - INVALID_TEMPLATE_CONFIG
            - HTTP_EXCEPTION
            - OTHERS
            - TEST
          type: string
        lastUpdated:
          format: int64
          type: integer
        message:
          type: string
      type: object
    EventsMessageDetails:
      description: Message details
      properties:
        i18nKey:
          description: Internationalization key
          type: string
        statusCode:
          description: Status code
          format: int32
          type: integer
        subject:
          description: Subject
          type: string
      type: object
    EventsNotificationFieldsConfig:
      properties:
        aliasField:
          description: Alias field
          type: string
        displayName:
          description: Display name
          type: string
        fieldName:
          description: Field name
          type: string
        maxLength:
          description: Maximum length
          format: int32
          type: integer
        options:
          items:
            $ref: "#/components/schemas/EventsFieldConfigOption"
          type: array
        redlockMapping:
          description: true = Prisma Cloud will provide the field value for notification
          type: boolean
        required:
          description: true = Required
          type: boolean
        type:
          description: Type of field
          enum:
            - list
            - text
            - array
            - bool
            - integer
          type: string
        typeaheadUri:
          description: URL used to query suggestions for field value
          type: string
        value:
          description: Field value
          type: string
      type: object
    EventsNotificationTemplate:
      properties:
        createdBy:
          description: User who created the notification template
          type: string
        createdTs:
          description: Creation Unix timestamp in milliseconds
          format: int64
          type: integer
        enabled:
          description: true = Enabled
          type: boolean
        id:
          description: Notification template ID
          type: string
        integrationId:
          description: Integration ID
          type: string
        integrationName:
          description: Integration name
          type: string
        integrationType:
          description: Integration type
          enum:
            - email
            - jira
            - service_now
          type: string
        lastModifiedBy:
          description: User who modified template last
          type: string
        lastModifiedTs:
          description: Modification Unix timestamp in milliseconds
          format: int64
          type: integer
        name:
          description: |
            Name. Cannot include special characters ('<', '>', '!', '=', '\n', '\r'). Maximum length is 99.
          type: string
        reason:
          $ref: "#/components/schemas/EventsIntegrationStatusDetails"
        status:
          description: Integration status color
          enum:
            - GREEN
            - RED
            - YELLOW
            - NA
          type: string
        templateConfig:
          additionalProperties:
            items:
              $ref: "#/components/schemas/EventsNotificationFieldsConfig"
            type: array
          type: object
        templateType:
          description: Template type
          enum:
            - ticketing
          type: string
        valid:
          description: true = Valid
          type: boolean
      required:
        - customerId
        - integrationType
        - name
      type: object
    EventsTestTemplateRequest:
      properties:
        integrationId:
          description: Integration ID
          type: string
        integrationType:
          description: Integration type
          enum:
            - email
            - jira
            - service_now
          type: string
        name:
          description: Template name
          type: string
        templateConfig:
          additionalProperties:
            description: Template Config
            items:
              $ref: "#/components/schemas/EventsNotificationFieldsConfig"
            type: array
          description: Template Config
          type: object
      required:
        - integrationId
        - integrationType
        - name
        - templateConfig
      type: object
info:
  contact: {}
  description: |
    Notification templates allow you to configure notifications about the Prisma Cloud alerts to:

    * Email 
    * ServiceNow 
    * Jira

  title: Prisma Cloud Notification Template V1 API
  version: Latest
openapi: 3.0.3
paths:
  /api/v1/tenant/{prismaId}/template:
    get:
      description: |
        Returns a list of notification templates. 

        The caller must have one of the following Prisma Cloud roles:

        * System Admin
        * Account Group Admin
        * Account and Cloud Provisioning Admin
        * Account Group Read Only

      operationId: get-all-templates-v1
      parameters:
        - description: |
            Prisma ID. Your Prisma ID is available either from the response object of your 
            [API request to log in](/api/cloud/cspm/login#operation/app-login) or 
            from the licensing information in the Prisma Cloud console.
          in: path
          name: prismaId
          required: true
          schema:
            type: string
        - description: Comma-separated list of Template IDs
          in: query
          name: id
          required: false
          schema:
            items:
              type: string
            type: array
        - description: |
            Comma-separated list of integration types that support notification templates. 
            Valid values: 

            * email
            * jira
            * service_now

          in: query
          name: type
          required: false
          schema:
            items:
              type: string
            type: array
        - in: query
          description: true = Enabled
          name: enabled
          required: false
          schema:
            type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/EventsNotificationTemplate"
                type: array
          description: OK
        "429":
          description: Too Many Requests
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsApiError"
          description: default response
        "500":
          description: Internal Server Error
      security:
        - x-redlock-auth: []
      summary: List Templates
      tags:
        - Notification Templates
    post:
      description: |
        Creates a notification template. 
        The caller must have one of the following Prisma Cloud roles:

        * System Admin
        * Account and Cloud Provisioning Admin

      operationId: create-template-v1
      parameters:
        - description: |
            Prisma ID. Your Prisma ID is available either from the response object of your 
            [API request to log in](/api/cloud/cspm/login#operation/app-login) or 
            from the licensing information in the Prisma Cloud console.
          in: path
          name: prismaId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventsCreateTemplateRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsNotificationTemplate"
          description: OK
        "429":
          description: Too Many Requests
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsApiError"
          description: default response
        "500":
          description: Internal Server Error
      security:
        - x-redlock-auth: []
      summary: Add Template
      tags:
        - Notification Templates
  /api/v1/tenant/{prismaId}/template/{id}:
    get:
      description: |
        Returns the notification template with the specified ID. 

        The caller must have one of the following Prisma Cloud roles:

        * System Admin
        * Account Group Admin
        * Account and Cloud Provisioning Admin
        * Account Group Read  Only

      operationId: get-template-v1
      parameters:
        - description: |
            Prisma ID. Your Prisma ID is available either from the response object of your 
            [API request to log in](/api/cloud/cspm/login#operation/app-login) or 
            from the licensing information in the Prisma Cloud console.
          in: path
          name: prismaId
          required: true
          schema:
            type: string
        - description: Template Id
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsNotificationTemplate"
          description: OK
        "429":
          description: Too many requests
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsApiError"
          description: default response
        "500":
          description: Internal server error
      security:
        - x-redlock-auth: []
      summary: Get Template by ID
      tags:
        - Notification Templates
    patch:
      description: |
        Updates the template with the specified ID. 
        The caller must have one of the following Prisma Cloud roles:

        * System Admin
        * Account and Cloud Provisioning Admin

      operationId: update-template-v1
      parameters:
        - description: |
            Prisma ID. Your Prisma ID is available either from the response object of your 
            [API request to log in](/api/cloud/cspm/login#operation/app-login) or 
            from the licensing information in the Prisma Cloud console.
          in: path
          name: prismaId
          required: true
          schema:
            type: string
        - description: Template ID
          in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventsNotificationTemplate"
        required: true
      responses:
        "200":
          description: OK
        "429":
          description: Too Many Requests
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsApiError"
          description: default response
        "500":
          description: Internal Server Error
      security:
        - x-redlock-auth: []
      summary: Update Template
      tags:
        - Notification Templates
    delete:
      description: |
        Deletes a template with the specified ID.

        The caller must have one of the following Prisma Cloud roles:

        * System Admin
        * Account and Cloud Provisioning Admin

      operationId: delete-template-v1
      parameters:
        - description: |
            Prisma ID. Your Prisma ID is available either from the response object of your 
            [API request to log in](/api/cloud/cspm/login#operation/app-login) or 
            from the licensing information in the Prisma Cloud console.
          in: path
          name: prismaId
          required: true
          schema:
            type: string
        - description: Template Id
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "429":
          description: Too Many Requests
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsApiError"
          description: default response
        "500":
          description: Internal Server Error
      security:
        - x-redlock-auth: []
      summary: Delete Template
      tags:
        - Notification Templates
  /api/v1/tenant/{prismaId}/template/test:
    post:
      description: |
        Runs a test of the notification template for the specified data. 

        The caller must have one of the following Prisma Cloud roles:

        * System Admin
        * Account and Cloud Provisioning Admin

      operationId: test-template-v1
      parameters:
        - description: |
            Prisma ID. Your Prisma ID is available either from the response object of your 
            [API request to log in](/api/cloud/cspm/login#operation/app-login) or 
            from the licensing information in the Prisma Cloud console.
          in: path
          name: prismaId
          required: true
          schema:
            type: string
        - description: Template ID
          in: query
          name: id
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventsTestTemplateRequest"
        required: true
      responses:
        "200":
          description: OK
        "429":
          description: Too Many Requests
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventsApiError"
          description: default response
        "500":
          description: Internal Server Error
      security:
        - x-redlock-auth: []
      summary: Test Template
      tags:
        - Notification Templates
servers:
  - url: https://api.prismacloud.io
tags:
  - description: The Notification Template endpoints are listed below.
    name: Notification Templates
