components:
  requestBodies:
    UserRoleModel:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UserRoleModel"
      description: User Role
      required: true
  securitySchemes:
    x-redlock-auth:
      description: The x-redlock-auth value is a JSON Web Token (JWT).
      in: header
      name: x-redlock-auth
      type: apiKey
  schemas:
    Attributes:
      description: Additional attributes of the the user role
      properties:
        hasDefenderPermissions:
          description: User has compute defender permissions
          type: boolean
        onlyAllowCIAccess:
          description:
            User can only use access keys to use Prisma Cloud. UI access
            will be unavailable.
          type: boolean
        onlyAllowComputeAccess:
          description: User can only access the Prisma Cloud Compute Console
          type: boolean
      type: object
    UserRoleModel:
      description: Model for User Role
      properties:
        accountGroupIds:
          description: Accessible Account Group IDs
          items:
            type: string
          type: array
        additionalAttributes:
          allOf:
            - $ref: "#/components/schemas/Attributes"
            - description: Additional attributes of the the user role
        associatedUsers:
          description:
            Associated application users which cannot exist in the system
            without the user role
          items:
            type: string
          readOnly: true
          type: array
        description:
          description: Description
          type: string
        id:
          description: User Role ID
          readOnly: true
          type: string
        lastModifiedBy:
          description: Last Modified By
          readOnly: true
          type: string
        lastModifiedTs:
          description: Last Modified Time
          format: int64
          readOnly: true
          type: integer
        name:
          description: Name
          type: string
        resourceListIds:
          description: Accessible Resource List IDs
          items:
            type: string
          type: array
        restrictDismissalAccess:
          type: boolean
        roleType:
          description: User Role Type
          enum:
            - System Admin
            - Account Group Admin
            - Account Group Read Only
            - Cloud Provisioning Admin
            - Account and Cloud Provisioning Admin
            - Build and Deploy Security
          type: string
      required:
        - name
        - roleType
      type: object
    UserRoleViewModel:
      description: Model for User Role View
      properties:
        accountGroupIds:
          description: Accessible Account Group IDs
          items:
            type: string
          type: array
        accountGroups:
          description: Associated Account Groups
          items:
            additionalProperties:
              type: string
            type: object
          readOnly: true
          type: array
        additionalAttributes:
          allOf:
            - $ref: "#/components/schemas/Attributes"
            - description: Additional attributes of the the user role
        associatedUsers:
          description:
            Associated application users which cannot exist in the system
            without the user role
          items:
            type: string
          readOnly: true
          type: array
        description:
          description: Description
          type: string
        id:
          description: User Role ID
          readOnly: true
          type: string
        lastModifiedBy:
          description: Last Modified By
          readOnly: true
          type: string
        lastModifiedTs:
          description: Last Modified Time
          format: int64
          readOnly: true
          type: integer
        name:
          description: Name
          type: string
        resourceListIds:
          description: Accessible Resource List IDs
          items:
            type: string
          type: array
        restrictDismissalAccess:
          type: boolean
        roleType:
          description: User Role Type
          enum:
            - System Admin
            - Account Group Admin
            - Account Group Read Only
            - Cloud Provisioning Admin
            - Account and Cloud Provisioning Admin
            - Build and Deploy Security
          type: string
      required:
        - name
        - roleType
      type: object
info:
  contact: {}
  description: "Manage your Prisma Cloud user roles.            \n"
  title: Prisma Cloud User Roles API Overview
  version: Latest
openapi: 3.0.0
paths:
  /user/role:
    get:
      description: Returns an array of user roles.
      operationId: get-user-roles
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/UserRoleViewModel"
                type: array
          description: successful operation
        "403":
          description: unauthorized_access
        "500":
          description: internal_error
      security:
        - x-redlock-auth: []
      summary: List User Roles
      tags:
        - User Roles
    post:
      description:
        "Creates a new user role.  \r\n\r\nSee [Prisma Cloud Administrator\
        \ Permissions](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/manage-prisma-cloud-administrators/prisma-cloud-admin-permissions.html)\
        \ \nfor the permissions associated with each role.\n\nNote that the request\
        \ body parameter **accountGroupIds** is required but can be an empty array.\n"
      operationId: add-user-role
      requestBody:
        $ref: "#/components/requestBodies/UserRoleModel"
      responses:
        "200":
          description: successful operation
        "400":
          description:
            invalid_user_role_name / invalid_user_role_type / invalid_account_group_ids
            / user_role_name_already_exists
        "403":
          description: unauthorized_access
        "500":
          description: internal_error
      security:
        - x-redlock-auth: []
      summary: Add User Role
      tags:
        - User Roles
  /user/role/name:
    get:
      description: Returns list of user role IDs and names.
      operationId: get-user-role-name
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  additionalProperties:
                    type: string
                  type: object
                type: array
          description: successful operation
        "403":
          description: unauthorized_access
        "500":
          description: internal_error
      security:
        - x-redlock-auth: []
      summary: List User Role Names
      tags:
        - User Roles
  /user/role/{id}:
    get:
      description: Returns user role information for a specified ID.
      operationId: get-user-role
      parameters:
        - description: User Role ID
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRoleViewModel"
          description: successful operation
        "400":
          description: invalid_id
        "403":
          description: unauthorized_access
        "500":
          description: internal_error
      security:
        - x-redlock-auth: []
      summary: User Role Info
      tags:
        - User Roles
    put:
      description: Updates information for an existing user role.
      operationId: update-user-role
      parameters:
        - description: User Role ID
          in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/UserRoleModel"
      responses:
        "200":
          description: successful operation
        "400":
          description:
            invalid_id / invalid_user_role_name / invalid_user_role_type
            / invalid_account_group_ids / user_role_name_already_exists
        "403":
          description: unauthorized_access
        "500":
          description: internal_error
      security:
        - x-redlock-auth: []
      summary: Update User Role
      tags:
        - User Roles
    delete:
      description: Deletes a user role with the specified ID.
      operationId: delete-user-role
      parameters:
        - description: User Role ID
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
        "400":
          description: invalid_id / cannot_delete_role_users_associated / invalid_id
        "403":
          description: unauthorized_access
        "500":
          description: internal_error
      security:
        - x-redlock-auth: []
      summary: Delete User Role
      tags:
        - User Roles
servers:
  - url: https://api.prismacloud.io
tags:
  - description: The User Role endpoints are listed below.
    name: User Roles
