name: Build Performance

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - demo/docs/**

permissions: {}

concurrency:
  group: build-perf-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build-size:
    if: ${{ github.repository == 'PaloAltoNetworks/docusaurus-openapi-docs' }}
    name: Build Size Report
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22"
          cache: yarn
      - uses: preactjs/compressed-size-action@66325aad6443cb7cf89c4bfcd414aea2367cda94 # v2.9.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build
          clean-script: clean
          pattern: "{demo/build/assets/js/main*js,demo/build/assets/js/runtime~main*js,demo/build/assets/css/styles*css,demo/.docusaurus/globalData.json,demo/.docusaurus/registry.js,demo/.docusaurus/routes.js,demo/.docusaurus/routesChunkNames.json,demo/.docusaurus/site-metadata.json,demo/.docusaurus/codeTranslations.json,demo/.docusaurus/i18n.json,demo/.docusaurus/docusaurus.config.mjs,demo/build/index.html,demo/build/petstore/**/*.html}"
          strip-hash: '\.([^;]\w{7})\.'
          minimum-change-threshold: 30
          compression: none

  build-time:
    if: ${{ github.repository == 'PaloAltoNetworks/docusaurus-openapi-docs' }}
    name: Build Time Perf
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22"
          cache: yarn
      - name: Installation
        run: yarn --frozen-lockfile --prefer-offline --ignore-scripts

      # Ensure build with a cold cache does not increase too much
      - name: Build (cold cache)
        run: yarn build
        timeout-minutes: 8

      # Ensure build with a warm cache does not increase too much
      - name: Build (warm cache)
        run: yarn build
        timeout-minutes: 2
    # TODO post a Github comment with build with perf warnings?
