name: Canary Release

on:
  push:
    branches:
      - main
    paths:
      - packages/**

permissions:
  contents: read
  id-token: write

jobs:
  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'PaloAltoNetworks/docusaurus-openapi-docs' && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # Needed to get the commit number with "git rev-list --count HEAD"
      - name: Set up Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: yarn
      - name: Prepare git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch
          git checkout main
      - name: Installation
        run: yarn && yarn build-packages
      - name: Publish Canary release
        run: |
          yarn canary
