name: Canary Beta Release

on:
  push:
    branches:
      - v3.0.0
    paths:
      - packages/**

permissions:
  contents: read

jobs:
  publish-canary:
    name: Publish Canary Beta
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'PaloAltoNetworks/docusaurus-openapi-docs' && github.ref == 'refs/heads/v3.0.0' && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # Needed to get the commit number with "git rev-list --count HEAD"
      - name: Set up Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "20"
          cache: yarn
      - name: Prepare git
        run: |
          git config --global user.name "Steven Serrata"
          git config --global user.email "sserrata@paloaltonetworks.com"
          git fetch
          git checkout v3.0.0
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Installation
        run: yarn && yarn build-packages
      - name: Publish Canary release
        run: |
          yarn canaryBeta
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
