name: PR Title Check

on:
  pull_request:
    branches:
      - main
      - v3.0.0
      - v2.0.0
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions: {}

jobs:
  check:
    if: ${{ github.repository == 'PaloAltoNetworks/docusaurus-openapi-docs' }}
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check
        run: npx ts-node --transpile-only scripts/check-pr-title.ts "$PR_TITLE"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
