name: Release

on:
  push:
    branches:
      - main
      - v2.0.0
  workflow_dispatch:

env:
  FORCE_COLOR: true

permissions: {}

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'PaloAltoNetworks/docusaurus-openapi-docs' }}
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true # scripts/publish.ts pushes tags via git
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline --ignore-scripts
      - name: Release
        run: yarn ts-node --transpile-only scripts/publish.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'PaloAltoNetworks/docusaurus-openapi-docs' && github.ref == 'refs/heads/main' }}
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check if packages changed
        id: packages_changed
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] || git diff --name-only HEAD~1 HEAD | grep -q "^packages/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up Node
        if: steps.packages_changed.outputs.changed == 'true'
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - name: Prepare git
        if: steps.packages_changed.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch
          git checkout main
      - name: Installation
        if: steps.packages_changed.outputs.changed == 'true'
        run: yarn --frozen-lockfile --prefer-offline --ignore-scripts && yarn build-packages
      - name: Publish Canary release
        if: steps.packages_changed.outputs.changed == 'true'
        run: yarn canary
