openapi: 3.0.3
info:
  title: Webhook Example
  version: 1.0.0
paths: {}
webhooks:
  order.created:
    post:
      requestBody:
        description: example body
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
